name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        for test_file in tests/test_*.py; do
          echo "Running tests in $test_file"
          python -m unittest $test_file
          if [ $? -eq 0 ]; then
            echo "$test_file executed successfully"
          else
            echo "$test_file failed"
          fi
        done
